import {observable} from 'mobx';
import {createContext} from 'react';

class ApiStore {
    @observable news = [
        {
            id: 1,
            title: 'Забег на набережной',
            short_description: 'Мастер спорта международного класса по спортивной акробатике. Многократная чемпионка РК, чемп...',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nulla aliquet porttitor lacus luctus accumsan. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Nibh sed pulvinar proin gravida hendrerit lectus. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Ut enim blandit volutpat maecenas volutpat blandit. Neque sodales ut etiam sit amet nisl. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Facilisis leo vel fringilla est ullamcorper eget nulla. Massa vitae tortor condimentum lacinia quis vel eros donec ac. Vestibulum sed arcu non odio euismod. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Interdum velit euismod in pellentesque.\n' +
                '\n' +
                'Sollicitudin tempor id eu nisl nunc mi. Velit sed ullamcorper morbi tincidunt ornare massa eget. Pellentesque pulvinar pellentesque habitant morbi tristique. Sed adipiscing diam donec adipiscing. Elit pellentesque habitant morbi tristique senectus et netus. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Leo a diam sollicitudin tempor id. Sapien et ligula ullamcorper malesuada proin libero. Bibendum est ultricies integer quis auctor elit. Accumsan sit amet nulla facilisi. Nunc sed blandit libero volutpat sed cras ornare arcu. Eget mi proin sed libero enim sed faucibus turpis. Amet luctus venenatis lectus magna fringilla urna. Lacinia quis vel eros donec ac odio tempor. Ipsum faucibus vitae aliquet nec ullamcorper. Et malesuada fames ac turpis. Nibh tellus molestie nunc non blandit massa enim nec dui. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Sit amet facilisis magna etiam tempor. Leo duis ut diam quam.\n' +
                '\n' +
                'Euismod lacinia at quis risus sed vulputate odio ut. Sit amet risus nullam eget felis eget nunc. Tortor vitae purus faucibus ornare suspendisse sed. Massa tincidunt nunc pulvinar sapien. Tellus integer feugiat scelerisque varius morbi. Leo duis ut diam quam nulla porttitor massa id neque. Etiam erat velit scelerisque in dictum. Dictum fusce ut placerat orci. Cursus sit amet dictum sit amet justo. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Integer quis auctor elit sed vulputate mi sit. Felis donec et odio pellentesque diam. Enim diam vulputate ut pharetra sit amet aliquam id diam. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Dignissim convallis aenean et tortor at risus viverra. Elementum curabitur vitae nunc sed velit.\n' +
                '\n' +
                'Urna cursus eget nunc scelerisque viverra mauris in. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Commodo viverra maecenas accumsan lacus vel. Lectus nulla at volutpat diam ut venenatis. Adipiscing elit duis tristique sollicitudin. Laoreet id donec ultrices tincidunt arcu non sodales. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Urna nec tincidunt praesent semper. Posuere morbi leo urna molestie at elementum eu facilisis sed. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus.\n' +
                '\n' +
                'Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Congue quisque egestas diam in arcu cursus. Egestas sed sed risus pretium. Scelerisque varius morbi enim nunc faucibus. Porttitor rhoncus dolor purus non enim praesent elementum. Habitasse platea dictumst quisque sagittis purus sit. Donec adipiscing tristique risus nec feugiat in fermentum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Et leo duis ut diam quam nulla porttitor. Viverra ipsum nunc aliquet bibendum enim. Tellus mauris a diam maecenas sed. Quis hendrerit dolor magna eget est lorem ipsum. Scelerisque purus semper eget duis at.\n' +
                '\n' +
                'Ultrices dui sapien eget mi proin. Sollicitudin nibh sit amet commodo nulla. A iaculis at erat pellentesque adipiscing commodo elit at. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Amet venenatis urna cursus eget nunc. Ante metus dictum at tempor commodo ullamcorper. Eu feugiat pretium nibh ipsum consequat nisl. Id cursus metus aliquam eleifend mi in. In ante metus dictum at tempor commodo ullamcorper a. Enim ut sem viverra aliquet eget sit amet. Integer quis auctor elit sed vulputate mi. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. A scelerisque purus semper eget duis at. Eget lorem dolor sed viverra ipsum. Vitae turpis massa sed elementum tempus egestas sed. Scelerisque viverra mauris in aliquam sem fringilla. Metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet consectetur adipiscing elit ut aliquam purus sit. Leo integer malesuada nunc vel risus commodo. Montes nascetur ridiculus mus mauris vitae ultricies leo.\n' +
                '\n' +
                'Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Ipsum suspendisse ultrices gravida dictum fusce. Pharetra sit amet aliquam id diam maecenas ultricies. Commodo viverra maecenas accumsan lacus vel facilisis. Ut consequat semper viverra nam libero justo laoreet. Id aliquet lectus proin nibh nisl condimentum. Libero nunc consequat interdum varius sit. Nec ultrices dui sapien eget mi proin sed libero. Proin sed libero enim sed. Etiam erat velit scelerisque in dictum non. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. In egestas erat imperdiet sed euismod nisi porta. Venenatis lectus magna fringilla urna. Nibh tellus molestie nunc non blandit massa enim nec dui. Neque laoreet suspendisse interdum consectetur libero id faucibus. Euismod in pellentesque massa placerat duis ultricies. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique.\n' +
                '\n' +
                'Sed velit dignissim sodales ut. Vitae auctor eu augue ut lectus arcu bibendum. Amet est placerat in egestas erat imperdiet sed. Amet mauris commodo quis imperdiet massa. Aliquam ultrices sagittis orci a scelerisque purus semper. Faucibus et molestie ac feugiat sed lectus. Dictumst vestibulum rhoncus est pellentesque. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Scelerisque eu ultrices vitae auctor eu augue ut. Volutpat commodo sed egestas egestas fringilla. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Sit amet porttitor eget dolor morbi non arcu risus. Egestas integer eget aliquet nibh praesent tristique. Urna neque viverra justo nec ultrices dui sapien eget mi. Nunc id cursus metus aliquam eleifend.\n' +
                '\n' +
                'Vulputate odio ut enim blandit volutpat maecenas volutpat. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Placerat orci nulla pellentesque dignissim enim. Mattis nunc sed blandit libero volutpat sed. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Dignissim convallis aenean et tortor at risus. Arcu dictum varius duis at consectetur lorem donec massa sapien. Bibendum neque egestas congue quisque egestas diam in. Sollicitudin tempor id eu nisl nunc mi. Vulputate mi sit amet mauris commodo quis imperdiet massa. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Ut venenatis tellus in metus. Suspendisse ultrices gravida dictum fusce ut. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Sed adipiscing diam donec adipiscing tristique. Tellus integer feugiat scelerisque varius morbi enim. Blandit massa enim nec dui nunc mattis enim ut tellus. Enim neque volutpat ac tincidunt vitae. Erat nam at lectus urna duis convallis convallis tellus id.\n' +
                '\n' +
                'Habitant morbi tristique senectus et netus. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Tempor id eu nisl nunc. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Elementum nibh tellus molestie nunc non blandit massa enim nec. Morbi enim nunc faucibus a. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Tincidunt vitae semper quis lectus nulla at.',
            date_formatted: '01.07.2023',
            image: 'https://picsum.photos/800/800'
        },
        {
            id: 2,
            title: 'Забег на набережной',
            short_description: 'Мастер спорта международного класса по спортивной акробатике. Многократная чемпионка РК, чемп...',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nulla aliquet porttitor lacus luctus accumsan. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Nibh sed pulvinar proin gravida hendrerit lectus. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Ut enim blandit volutpat maecenas volutpat blandit. Neque sodales ut etiam sit amet nisl. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Facilisis leo vel fringilla est ullamcorper eget nulla. Massa vitae tortor condimentum lacinia quis vel eros donec ac. Vestibulum sed arcu non odio euismod. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Interdum velit euismod in pellentesque.\n' +
                '\n' +
                'Sollicitudin tempor id eu nisl nunc mi. Velit sed ullamcorper morbi tincidunt ornare massa eget. Pellentesque pulvinar pellentesque habitant morbi tristique. Sed adipiscing diam donec adipiscing. Elit pellentesque habitant morbi tristique senectus et netus. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Leo a diam sollicitudin tempor id. Sapien et ligula ullamcorper malesuada proin libero. Bibendum est ultricies integer quis auctor elit. Accumsan sit amet nulla facilisi. Nunc sed blandit libero volutpat sed cras ornare arcu. Eget mi proin sed libero enim sed faucibus turpis. Amet luctus venenatis lectus magna fringilla urna. Lacinia quis vel eros donec ac odio tempor. Ipsum faucibus vitae aliquet nec ullamcorper. Et malesuada fames ac turpis. Nibh tellus molestie nunc non blandit massa enim nec dui. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Sit amet facilisis magna etiam tempor. Leo duis ut diam quam.\n' +
                '\n' +
                'Euismod lacinia at quis risus sed vulputate odio ut. Sit amet risus nullam eget felis eget nunc. Tortor vitae purus faucibus ornare suspendisse sed. Massa tincidunt nunc pulvinar sapien. Tellus integer feugiat scelerisque varius morbi. Leo duis ut diam quam nulla porttitor massa id neque. Etiam erat velit scelerisque in dictum. Dictum fusce ut placerat orci. Cursus sit amet dictum sit amet justo. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Integer quis auctor elit sed vulputate mi sit. Felis donec et odio pellentesque diam. Enim diam vulputate ut pharetra sit amet aliquam id diam. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Dignissim convallis aenean et tortor at risus viverra. Elementum curabitur vitae nunc sed velit.\n' +
                '\n' +
                'Urna cursus eget nunc scelerisque viverra mauris in. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Commodo viverra maecenas accumsan lacus vel. Lectus nulla at volutpat diam ut venenatis. Adipiscing elit duis tristique sollicitudin. Laoreet id donec ultrices tincidunt arcu non sodales. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Urna nec tincidunt praesent semper. Posuere morbi leo urna molestie at elementum eu facilisis sed. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus.\n' +
                '\n' +
                'Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Congue quisque egestas diam in arcu cursus. Egestas sed sed risus pretium. Scelerisque varius morbi enim nunc faucibus. Porttitor rhoncus dolor purus non enim praesent elementum. Habitasse platea dictumst quisque sagittis purus sit. Donec adipiscing tristique risus nec feugiat in fermentum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Et leo duis ut diam quam nulla porttitor. Viverra ipsum nunc aliquet bibendum enim. Tellus mauris a diam maecenas sed. Quis hendrerit dolor magna eget est lorem ipsum. Scelerisque purus semper eget duis at.\n' +
                '\n' +
                'Ultrices dui sapien eget mi proin. Sollicitudin nibh sit amet commodo nulla. A iaculis at erat pellentesque adipiscing commodo elit at. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Amet venenatis urna cursus eget nunc. Ante metus dictum at tempor commodo ullamcorper. Eu feugiat pretium nibh ipsum consequat nisl. Id cursus metus aliquam eleifend mi in. In ante metus dictum at tempor commodo ullamcorper a. Enim ut sem viverra aliquet eget sit amet. Integer quis auctor elit sed vulputate mi. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. A scelerisque purus semper eget duis at. Eget lorem dolor sed viverra ipsum. Vitae turpis massa sed elementum tempus egestas sed. Scelerisque viverra mauris in aliquam sem fringilla. Metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet consectetur adipiscing elit ut aliquam purus sit. Leo integer malesuada nunc vel risus commodo. Montes nascetur ridiculus mus mauris vitae ultricies leo.\n' +
                '\n' +
                'Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Ipsum suspendisse ultrices gravida dictum fusce. Pharetra sit amet aliquam id diam maecenas ultricies. Commodo viverra maecenas accumsan lacus vel facilisis. Ut consequat semper viverra nam libero justo laoreet. Id aliquet lectus proin nibh nisl condimentum. Libero nunc consequat interdum varius sit. Nec ultrices dui sapien eget mi proin sed libero. Proin sed libero enim sed. Etiam erat velit scelerisque in dictum non. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. In egestas erat imperdiet sed euismod nisi porta. Venenatis lectus magna fringilla urna. Nibh tellus molestie nunc non blandit massa enim nec dui. Neque laoreet suspendisse interdum consectetur libero id faucibus. Euismod in pellentesque massa placerat duis ultricies. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique.\n' +
                '\n' +
                'Sed velit dignissim sodales ut. Vitae auctor eu augue ut lectus arcu bibendum. Amet est placerat in egestas erat imperdiet sed. Amet mauris commodo quis imperdiet massa. Aliquam ultrices sagittis orci a scelerisque purus semper. Faucibus et molestie ac feugiat sed lectus. Dictumst vestibulum rhoncus est pellentesque. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Scelerisque eu ultrices vitae auctor eu augue ut. Volutpat commodo sed egestas egestas fringilla. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Sit amet porttitor eget dolor morbi non arcu risus. Egestas integer eget aliquet nibh praesent tristique. Urna neque viverra justo nec ultrices dui sapien eget mi. Nunc id cursus metus aliquam eleifend.\n' +
                '\n' +
                'Vulputate odio ut enim blandit volutpat maecenas volutpat. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Placerat orci nulla pellentesque dignissim enim. Mattis nunc sed blandit libero volutpat sed. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Dignissim convallis aenean et tortor at risus. Arcu dictum varius duis at consectetur lorem donec massa sapien. Bibendum neque egestas congue quisque egestas diam in. Sollicitudin tempor id eu nisl nunc mi. Vulputate mi sit amet mauris commodo quis imperdiet massa. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Ut venenatis tellus in metus. Suspendisse ultrices gravida dictum fusce ut. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Sed adipiscing diam donec adipiscing tristique. Tellus integer feugiat scelerisque varius morbi enim. Blandit massa enim nec dui nunc mattis enim ut tellus. Enim neque volutpat ac tincidunt vitae. Erat nam at lectus urna duis convallis convallis tellus id.\n' +
                '\n' +
                'Habitant morbi tristique senectus et netus. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Tempor id eu nisl nunc. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Elementum nibh tellus molestie nunc non blandit massa enim nec. Morbi enim nunc faucibus a. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Tincidunt vitae semper quis lectus nulla at.',
            date_formatted: '01.07.2023',
            image: 'https://picsum.photos/800/800'
        },
        {
            id: 3,
            title: 'Забег на набережной',
            short_description: 'Мастер спорта международного класса по спортивной акробатике. Многократная чемпионка РК, чемп...',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nulla aliquet porttitor lacus luctus accumsan. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Nibh sed pulvinar proin gravida hendrerit lectus. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Ut enim blandit volutpat maecenas volutpat blandit. Neque sodales ut etiam sit amet nisl. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Facilisis leo vel fringilla est ullamcorper eget nulla. Massa vitae tortor condimentum lacinia quis vel eros donec ac. Vestibulum sed arcu non odio euismod. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Interdum velit euismod in pellentesque.\n' +
                '\n' +
                'Sollicitudin tempor id eu nisl nunc mi. Velit sed ullamcorper morbi tincidunt ornare massa eget. Pellentesque pulvinar pellentesque habitant morbi tristique. Sed adipiscing diam donec adipiscing. Elit pellentesque habitant morbi tristique senectus et netus. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Leo a diam sollicitudin tempor id. Sapien et ligula ullamcorper malesuada proin libero. Bibendum est ultricies integer quis auctor elit. Accumsan sit amet nulla facilisi. Nunc sed blandit libero volutpat sed cras ornare arcu. Eget mi proin sed libero enim sed faucibus turpis. Amet luctus venenatis lectus magna fringilla urna. Lacinia quis vel eros donec ac odio tempor. Ipsum faucibus vitae aliquet nec ullamcorper. Et malesuada fames ac turpis. Nibh tellus molestie nunc non blandit massa enim nec dui. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Sit amet facilisis magna etiam tempor. Leo duis ut diam quam.\n' +
                '\n' +
                'Euismod lacinia at quis risus sed vulputate odio ut. Sit amet risus nullam eget felis eget nunc. Tortor vitae purus faucibus ornare suspendisse sed. Massa tincidunt nunc pulvinar sapien. Tellus integer feugiat scelerisque varius morbi. Leo duis ut diam quam nulla porttitor massa id neque. Etiam erat velit scelerisque in dictum. Dictum fusce ut placerat orci. Cursus sit amet dictum sit amet justo. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Integer quis auctor elit sed vulputate mi sit. Felis donec et odio pellentesque diam. Enim diam vulputate ut pharetra sit amet aliquam id diam. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Dignissim convallis aenean et tortor at risus viverra. Elementum curabitur vitae nunc sed velit.\n' +
                '\n' +
                'Urna cursus eget nunc scelerisque viverra mauris in. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Commodo viverra maecenas accumsan lacus vel. Lectus nulla at volutpat diam ut venenatis. Adipiscing elit duis tristique sollicitudin. Laoreet id donec ultrices tincidunt arcu non sodales. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Urna nec tincidunt praesent semper. Posuere morbi leo urna molestie at elementum eu facilisis sed. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus.\n' +
                '\n' +
                'Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Congue quisque egestas diam in arcu cursus. Egestas sed sed risus pretium. Scelerisque varius morbi enim nunc faucibus. Porttitor rhoncus dolor purus non enim praesent elementum. Habitasse platea dictumst quisque sagittis purus sit. Donec adipiscing tristique risus nec feugiat in fermentum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Et leo duis ut diam quam nulla porttitor. Viverra ipsum nunc aliquet bibendum enim. Tellus mauris a diam maecenas sed. Quis hendrerit dolor magna eget est lorem ipsum. Scelerisque purus semper eget duis at.\n' +
                '\n' +
                'Ultrices dui sapien eget mi proin. Sollicitudin nibh sit amet commodo nulla. A iaculis at erat pellentesque adipiscing commodo elit at. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Amet venenatis urna cursus eget nunc. Ante metus dictum at tempor commodo ullamcorper. Eu feugiat pretium nibh ipsum consequat nisl. Id cursus metus aliquam eleifend mi in. In ante metus dictum at tempor commodo ullamcorper a. Enim ut sem viverra aliquet eget sit amet. Integer quis auctor elit sed vulputate mi. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. A scelerisque purus semper eget duis at. Eget lorem dolor sed viverra ipsum. Vitae turpis massa sed elementum tempus egestas sed. Scelerisque viverra mauris in aliquam sem fringilla. Metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet consectetur adipiscing elit ut aliquam purus sit. Leo integer malesuada nunc vel risus commodo. Montes nascetur ridiculus mus mauris vitae ultricies leo.\n' +
                '\n' +
                'Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Ipsum suspendisse ultrices gravida dictum fusce. Pharetra sit amet aliquam id diam maecenas ultricies. Commodo viverra maecenas accumsan lacus vel facilisis. Ut consequat semper viverra nam libero justo laoreet. Id aliquet lectus proin nibh nisl condimentum. Libero nunc consequat interdum varius sit. Nec ultrices dui sapien eget mi proin sed libero. Proin sed libero enim sed. Etiam erat velit scelerisque in dictum non. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. In egestas erat imperdiet sed euismod nisi porta. Venenatis lectus magna fringilla urna. Nibh tellus molestie nunc non blandit massa enim nec dui. Neque laoreet suspendisse interdum consectetur libero id faucibus. Euismod in pellentesque massa placerat duis ultricies. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique.\n' +
                '\n' +
                'Sed velit dignissim sodales ut. Vitae auctor eu augue ut lectus arcu bibendum. Amet est placerat in egestas erat imperdiet sed. Amet mauris commodo quis imperdiet massa. Aliquam ultrices sagittis orci a scelerisque purus semper. Faucibus et molestie ac feugiat sed lectus. Dictumst vestibulum rhoncus est pellentesque. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Scelerisque eu ultrices vitae auctor eu augue ut. Volutpat commodo sed egestas egestas fringilla. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Sit amet porttitor eget dolor morbi non arcu risus. Egestas integer eget aliquet nibh praesent tristique. Urna neque viverra justo nec ultrices dui sapien eget mi. Nunc id cursus metus aliquam eleifend.\n' +
                '\n' +
                'Vulputate odio ut enim blandit volutpat maecenas volutpat. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Placerat orci nulla pellentesque dignissim enim. Mattis nunc sed blandit libero volutpat sed. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Dignissim convallis aenean et tortor at risus. Arcu dictum varius duis at consectetur lorem donec massa sapien. Bibendum neque egestas congue quisque egestas diam in. Sollicitudin tempor id eu nisl nunc mi. Vulputate mi sit amet mauris commodo quis imperdiet massa. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Ut venenatis tellus in metus. Suspendisse ultrices gravida dictum fusce ut. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Sed adipiscing diam donec adipiscing tristique. Tellus integer feugiat scelerisque varius morbi enim. Blandit massa enim nec dui nunc mattis enim ut tellus. Enim neque volutpat ac tincidunt vitae. Erat nam at lectus urna duis convallis convallis tellus id.\n' +
                '\n' +
                'Habitant morbi tristique senectus et netus. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Tempor id eu nisl nunc. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Elementum nibh tellus molestie nunc non blandit massa enim nec. Morbi enim nunc faucibus a. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Tincidunt vitae semper quis lectus nulla at.',
            date_formatted: '01.07.2023',
            image: 'https://picsum.photos/800/800'
        },
        {
            id: 4,
            title: 'Забег на набережной',
            short_description: 'Мастер спорта международного класса по спортивной акробатике. Многократная чемпионка РК, чемп...',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nulla aliquet porttitor lacus luctus accumsan. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Nibh sed pulvinar proin gravida hendrerit lectus. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Ut enim blandit volutpat maecenas volutpat blandit. Neque sodales ut etiam sit amet nisl. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Facilisis leo vel fringilla est ullamcorper eget nulla. Massa vitae tortor condimentum lacinia quis vel eros donec ac. Vestibulum sed arcu non odio euismod. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Interdum velit euismod in pellentesque.\n' +
                '\n' +
                'Sollicitudin tempor id eu nisl nunc mi. Velit sed ullamcorper morbi tincidunt ornare massa eget. Pellentesque pulvinar pellentesque habitant morbi tristique. Sed adipiscing diam donec adipiscing. Elit pellentesque habitant morbi tristique senectus et netus. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Leo a diam sollicitudin tempor id. Sapien et ligula ullamcorper malesuada proin libero. Bibendum est ultricies integer quis auctor elit. Accumsan sit amet nulla facilisi. Nunc sed blandit libero volutpat sed cras ornare arcu. Eget mi proin sed libero enim sed faucibus turpis. Amet luctus venenatis lectus magna fringilla urna. Lacinia quis vel eros donec ac odio tempor. Ipsum faucibus vitae aliquet nec ullamcorper. Et malesuada fames ac turpis. Nibh tellus molestie nunc non blandit massa enim nec dui. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Sit amet facilisis magna etiam tempor. Leo duis ut diam quam.\n' +
                '\n' +
                'Euismod lacinia at quis risus sed vulputate odio ut. Sit amet risus nullam eget felis eget nunc. Tortor vitae purus faucibus ornare suspendisse sed. Massa tincidunt nunc pulvinar sapien. Tellus integer feugiat scelerisque varius morbi. Leo duis ut diam quam nulla porttitor massa id neque. Etiam erat velit scelerisque in dictum. Dictum fusce ut placerat orci. Cursus sit amet dictum sit amet justo. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Integer quis auctor elit sed vulputate mi sit. Felis donec et odio pellentesque diam. Enim diam vulputate ut pharetra sit amet aliquam id diam. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Dignissim convallis aenean et tortor at risus viverra. Elementum curabitur vitae nunc sed velit.\n' +
                '\n' +
                'Urna cursus eget nunc scelerisque viverra mauris in. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Commodo viverra maecenas accumsan lacus vel. Lectus nulla at volutpat diam ut venenatis. Adipiscing elit duis tristique sollicitudin. Laoreet id donec ultrices tincidunt arcu non sodales. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Urna nec tincidunt praesent semper. Posuere morbi leo urna molestie at elementum eu facilisis sed. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus.\n' +
                '\n' +
                'Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Congue quisque egestas diam in arcu cursus. Egestas sed sed risus pretium. Scelerisque varius morbi enim nunc faucibus. Porttitor rhoncus dolor purus non enim praesent elementum. Habitasse platea dictumst quisque sagittis purus sit. Donec adipiscing tristique risus nec feugiat in fermentum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Et leo duis ut diam quam nulla porttitor. Viverra ipsum nunc aliquet bibendum enim. Tellus mauris a diam maecenas sed. Quis hendrerit dolor magna eget est lorem ipsum. Scelerisque purus semper eget duis at.\n' +
                '\n' +
                'Ultrices dui sapien eget mi proin. Sollicitudin nibh sit amet commodo nulla. A iaculis at erat pellentesque adipiscing commodo elit at. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Amet venenatis urna cursus eget nunc. Ante metus dictum at tempor commodo ullamcorper. Eu feugiat pretium nibh ipsum consequat nisl. Id cursus metus aliquam eleifend mi in. In ante metus dictum at tempor commodo ullamcorper a. Enim ut sem viverra aliquet eget sit amet. Integer quis auctor elit sed vulputate mi. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. A scelerisque purus semper eget duis at. Eget lorem dolor sed viverra ipsum. Vitae turpis massa sed elementum tempus egestas sed. Scelerisque viverra mauris in aliquam sem fringilla. Metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet consectetur adipiscing elit ut aliquam purus sit. Leo integer malesuada nunc vel risus commodo. Montes nascetur ridiculus mus mauris vitae ultricies leo.\n' +
                '\n' +
                'Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Ipsum suspendisse ultrices gravida dictum fusce. Pharetra sit amet aliquam id diam maecenas ultricies. Commodo viverra maecenas accumsan lacus vel facilisis. Ut consequat semper viverra nam libero justo laoreet. Id aliquet lectus proin nibh nisl condimentum. Libero nunc consequat interdum varius sit. Nec ultrices dui sapien eget mi proin sed libero. Proin sed libero enim sed. Etiam erat velit scelerisque in dictum non. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. In egestas erat imperdiet sed euismod nisi porta. Venenatis lectus magna fringilla urna. Nibh tellus molestie nunc non blandit massa enim nec dui. Neque laoreet suspendisse interdum consectetur libero id faucibus. Euismod in pellentesque massa placerat duis ultricies. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique.\n' +
                '\n' +
                'Sed velit dignissim sodales ut. Vitae auctor eu augue ut lectus arcu bibendum. Amet est placerat in egestas erat imperdiet sed. Amet mauris commodo quis imperdiet massa. Aliquam ultrices sagittis orci a scelerisque purus semper. Faucibus et molestie ac feugiat sed lectus. Dictumst vestibulum rhoncus est pellentesque. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Scelerisque eu ultrices vitae auctor eu augue ut. Volutpat commodo sed egestas egestas fringilla. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Sit amet porttitor eget dolor morbi non arcu risus. Egestas integer eget aliquet nibh praesent tristique. Urna neque viverra justo nec ultrices dui sapien eget mi. Nunc id cursus metus aliquam eleifend.\n' +
                '\n' +
                'Vulputate odio ut enim blandit volutpat maecenas volutpat. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Placerat orci nulla pellentesque dignissim enim. Mattis nunc sed blandit libero volutpat sed. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Dignissim convallis aenean et tortor at risus. Arcu dictum varius duis at consectetur lorem donec massa sapien. Bibendum neque egestas congue quisque egestas diam in. Sollicitudin tempor id eu nisl nunc mi. Vulputate mi sit amet mauris commodo quis imperdiet massa. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Ut venenatis tellus in metus. Suspendisse ultrices gravida dictum fusce ut. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Sed adipiscing diam donec adipiscing tristique. Tellus integer feugiat scelerisque varius morbi enim. Blandit massa enim nec dui nunc mattis enim ut tellus. Enim neque volutpat ac tincidunt vitae. Erat nam at lectus urna duis convallis convallis tellus id.\n' +
                '\n' +
                'Habitant morbi tristique senectus et netus. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Tempor id eu nisl nunc. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Elementum nibh tellus molestie nunc non blandit massa enim nec. Morbi enim nunc faucibus a. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Tincidunt vitae semper quis lectus nulla at.',
            date_formatted: '01.07.2023',
            image: 'https://picsum.photos/800/800'
        },
        {
            id: 5,
            title: 'Забег на набережной',
            short_description: 'Мастер спорта международного класса по спортивной акробатике. Многократная чемпионка РК, чемп...',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nulla aliquet porttitor lacus luctus accumsan. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Nibh sed pulvinar proin gravida hendrerit lectus. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Ut enim blandit volutpat maecenas volutpat blandit. Neque sodales ut etiam sit amet nisl. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Facilisis leo vel fringilla est ullamcorper eget nulla. Massa vitae tortor condimentum lacinia quis vel eros donec ac. Vestibulum sed arcu non odio euismod. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Interdum velit euismod in pellentesque.\n' +
                '\n' +
                'Sollicitudin tempor id eu nisl nunc mi. Velit sed ullamcorper morbi tincidunt ornare massa eget. Pellentesque pulvinar pellentesque habitant morbi tristique. Sed adipiscing diam donec adipiscing. Elit pellentesque habitant morbi tristique senectus et netus. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Leo a diam sollicitudin tempor id. Sapien et ligula ullamcorper malesuada proin libero. Bibendum est ultricies integer quis auctor elit. Accumsan sit amet nulla facilisi. Nunc sed blandit libero volutpat sed cras ornare arcu. Eget mi proin sed libero enim sed faucibus turpis. Amet luctus venenatis lectus magna fringilla urna. Lacinia quis vel eros donec ac odio tempor. Ipsum faucibus vitae aliquet nec ullamcorper. Et malesuada fames ac turpis. Nibh tellus molestie nunc non blandit massa enim nec dui. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Sit amet facilisis magna etiam tempor. Leo duis ut diam quam.\n' +
                '\n' +
                'Euismod lacinia at quis risus sed vulputate odio ut. Sit amet risus nullam eget felis eget nunc. Tortor vitae purus faucibus ornare suspendisse sed. Massa tincidunt nunc pulvinar sapien. Tellus integer feugiat scelerisque varius morbi. Leo duis ut diam quam nulla porttitor massa id neque. Etiam erat velit scelerisque in dictum. Dictum fusce ut placerat orci. Cursus sit amet dictum sit amet justo. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Integer quis auctor elit sed vulputate mi sit. Felis donec et odio pellentesque diam. Enim diam vulputate ut pharetra sit amet aliquam id diam. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Dignissim convallis aenean et tortor at risus viverra. Elementum curabitur vitae nunc sed velit.\n' +
                '\n' +
                'Urna cursus eget nunc scelerisque viverra mauris in. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Commodo viverra maecenas accumsan lacus vel. Lectus nulla at volutpat diam ut venenatis. Adipiscing elit duis tristique sollicitudin. Laoreet id donec ultrices tincidunt arcu non sodales. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Urna nec tincidunt praesent semper. Posuere morbi leo urna molestie at elementum eu facilisis sed. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus.\n' +
                '\n' +
                'Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Congue quisque egestas diam in arcu cursus. Egestas sed sed risus pretium. Scelerisque varius morbi enim nunc faucibus. Porttitor rhoncus dolor purus non enim praesent elementum. Habitasse platea dictumst quisque sagittis purus sit. Donec adipiscing tristique risus nec feugiat in fermentum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Et leo duis ut diam quam nulla porttitor. Viverra ipsum nunc aliquet bibendum enim. Tellus mauris a diam maecenas sed. Quis hendrerit dolor magna eget est lorem ipsum. Scelerisque purus semper eget duis at.\n' +
                '\n' +
                'Ultrices dui sapien eget mi proin. Sollicitudin nibh sit amet commodo nulla. A iaculis at erat pellentesque adipiscing commodo elit at. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Amet venenatis urna cursus eget nunc. Ante metus dictum at tempor commodo ullamcorper. Eu feugiat pretium nibh ipsum consequat nisl. Id cursus metus aliquam eleifend mi in. In ante metus dictum at tempor commodo ullamcorper a. Enim ut sem viverra aliquet eget sit amet. Integer quis auctor elit sed vulputate mi. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. A scelerisque purus semper eget duis at. Eget lorem dolor sed viverra ipsum. Vitae turpis massa sed elementum tempus egestas sed. Scelerisque viverra mauris in aliquam sem fringilla. Metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet consectetur adipiscing elit ut aliquam purus sit. Leo integer malesuada nunc vel risus commodo. Montes nascetur ridiculus mus mauris vitae ultricies leo.\n' +
                '\n' +
                'Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Ipsum suspendisse ultrices gravida dictum fusce. Pharetra sit amet aliquam id diam maecenas ultricies. Commodo viverra maecenas accumsan lacus vel facilisis. Ut consequat semper viverra nam libero justo laoreet. Id aliquet lectus proin nibh nisl condimentum. Libero nunc consequat interdum varius sit. Nec ultrices dui sapien eget mi proin sed libero. Proin sed libero enim sed. Etiam erat velit scelerisque in dictum non. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. In egestas erat imperdiet sed euismod nisi porta. Venenatis lectus magna fringilla urna. Nibh tellus molestie nunc non blandit massa enim nec dui. Neque laoreet suspendisse interdum consectetur libero id faucibus. Euismod in pellentesque massa placerat duis ultricies. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique.\n' +
                '\n' +
                'Sed velit dignissim sodales ut. Vitae auctor eu augue ut lectus arcu bibendum. Amet est placerat in egestas erat imperdiet sed. Amet mauris commodo quis imperdiet massa. Aliquam ultrices sagittis orci a scelerisque purus semper. Faucibus et molestie ac feugiat sed lectus. Dictumst vestibulum rhoncus est pellentesque. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Scelerisque eu ultrices vitae auctor eu augue ut. Volutpat commodo sed egestas egestas fringilla. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Sit amet porttitor eget dolor morbi non arcu risus. Egestas integer eget aliquet nibh praesent tristique. Urna neque viverra justo nec ultrices dui sapien eget mi. Nunc id cursus metus aliquam eleifend.\n' +
                '\n' +
                'Vulputate odio ut enim blandit volutpat maecenas volutpat. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Placerat orci nulla pellentesque dignissim enim. Mattis nunc sed blandit libero volutpat sed. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Dignissim convallis aenean et tortor at risus. Arcu dictum varius duis at consectetur lorem donec massa sapien. Bibendum neque egestas congue quisque egestas diam in. Sollicitudin tempor id eu nisl nunc mi. Vulputate mi sit amet mauris commodo quis imperdiet massa. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Ut venenatis tellus in metus. Suspendisse ultrices gravida dictum fusce ut. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Sed adipiscing diam donec adipiscing tristique. Tellus integer feugiat scelerisque varius morbi enim. Blandit massa enim nec dui nunc mattis enim ut tellus. Enim neque volutpat ac tincidunt vitae. Erat nam at lectus urna duis convallis convallis tellus id.\n' +
                '\n' +
                'Habitant morbi tristique senectus et netus. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Tempor id eu nisl nunc. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Elementum nibh tellus molestie nunc non blandit massa enim nec. Morbi enim nunc faucibus a. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Tincidunt vitae semper quis lectus nulla at.',
            date_formatted: '01.07.2023',
            image: 'https://picsum.photos/800/800'
        },
    ];
}

export default createContext(new ApiStore())
